name: Lint Code Base

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: PHP Linter

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: overtrue/phplint@9.1
        with:
          path: src
